name: OmsUserDbBukkit
version: 1.0.1
description: Calls OMS User DB API from Bukkit servers.
author: Our Minecraft Space
website: https://userdb.ourmc.space
main: space.ourmc.userdb.bukkit.OmsUserDbBukkit
softdepend: [ProtocolLib]
commands:
  userdb:
    description: Search OMS UserDb
    usage: /userdb [search <username>/get <UUID/username>]
    permission: userdb.command
permissions:
  userdb.command:
    description: userdb command
    default: op
  userdb.alert.receive:
    description: receive alert when a reported user joins
    default: op
  userdb.alert.bypass:
    description: bypass being alerted
    default: false
